### ISSUE TITLE
想问下图2的横纵坐标都是什么 

### ISSUE THREAD

**Issue by lllllialois** [YuzhenD/Resyn#1]

**Comment by YuzhenD** [comment]
图2的横轴指代的是复杂度数值，纵轴是数据集里面的图片，我们为每张图片计算了复杂度数值，之后按照从小到大的顺序排列，在纵轴上呈现出阶梯上升的感觉

**Comment by lllllialois** [comment]
正负是代表训练集和测试集吗 顺便问下表1的set5和set14都代表什么呢

**Comment by YuzhenD** [comment]
正负是复杂度数值的不同，与数据集无关。比方说Urban100数据集有100张测试图片，我们为每张图片计算了复杂度，那么复杂度的数值有正有负，按照从小到大的顺序排序，在纵轴上梯度上升。就可以直观看到在复杂度上的分布情况。

表一的 set5 和 set14 指代的是超分测试数据集

**Comment by YuzhenD** [comment]
set5 和 set14 数据集可以在:https://drive.google.com/file/d/1n-7pmwjP0isZBK7w3tx2y8CTastlABx1/view?usp=sharing 里下载，或者也可以在网上找到。因为两个数据集图片太少了，分别是 5 和 14，就没有在在图2里绘图了。

**Comment by lllllialois** [comment]
> 正负是复杂度数值的不同，与数据集无关。比方说Urban100数据集有100张测试图片，我们为每张图片计算了复杂度，那么复杂度的数值有正有负，按照从小到大的顺序排序，在纵轴上梯度上升。就可以直观看到在复杂度上的分布情况。
> 
> 表一的 set5 和 set14 指代的是超分测试数据集

好的 谢谢解答
